# https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
---
_extends: .github
tag-template: global-variable-string-parameter-$NEXT_MINOR_VERSION
version-template: $MAJOR.$MINOR.$PATCH
